services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./dev.db
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    restart: always

